import pandas as pd
df=pd.read_csv('titanic.csv')
print('Кол-во выживших')
print(df['Survived'].sum())
print('Процент выживших')
print('Всего:')
print(f'{df['Survived'].mean() * 100:.2f}')
print('Женщин:')
print(f'{df[df['Sex'] == 'female']['Survived'].mean() * 100:.2f}')
print('Мужчин:')
print(f'{df[df['Sex'] == 'male']['Survived'].mean() * 100:.2f}')